### ISSUE TITLE
DynamoDbException in WrappedHttpHandler error

### ISSUE THREAD

**Issue by nam-co** [baopham/laravel-dynamodb#44] opened 2017-03-04 14:12 UTC
Hello, Im trying to access/write messages in a Dynamodb table, but all Im getting is this when I try to get:

DynamoDbException in WrappedHttpHandler.php line 192: Error executing "GetItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: POST https://dynamodb.us-east-1.amazonaws.com resulted in a 400 Bad Request response: {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...) ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}

Im using a user with the necessary permissions Can somebody please help me thanks

**Comment by baopham** [comment] 2017-03-04 14:15
that sounds more like you didn't setup things right :

http://stackoverflow.com/questions/25886403/dynamodb-the-provided-key-element-does-not-match-the-schema

Can you give me your model class?

**Comment by nam-co** [comment] 2017-03-04 14:18
Thanks for the response, Im on L5.4, here is my model:
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Messages extends \BaoPham\DynamoDb\DynamoDbModel
{
	protected $table = 'Rebilling_messages';
}

**Comment by baopham** [comment] 2017-03-04 14:20
and what is your primary key in your DynamoDB table?

**Comment by nam-co** [comment] 2017-03-04 14:23
Primary: id (String), sort: create_at (String)

**Comment by baopham** [comment] 2017-03-04 14:23
can you give me the code that causes the error?

**Comment by nam-co** [comment] 2017-03-04 14:28
is a 2 part code, one gets where I get the error
$message3 = Messages::find(1); 

The second saves, this one doesn't give an error but it doesn't save anything on the table AWS console
$message = new Messages;
$message->id = uniqid('', true);
$message->save();

**Comment by baopham** [comment] 2017-03-04 14:34
So:
1.
`$message3 = Messages::find(1);` gives you error? are you passing in a string or a number? looks like your primary key should be string instead.

2. Are you sure your table only needs the `id`? you should fill in all other columns especially, `create_at`

**Comment by nam-co** [comment] 2017-03-04 14:41
this is an example of the table:
{
  "content": "TAMBIEN claro que si\n\npero con return?",
  "create_at": "2017-01-21 00:24:11",
  "files": [
    "the-file.jpg"
  ],
  "from": 1,
  "id": "1",
  "order_id": 1
}

**Comment by baopham** [comment] 2017-03-04 14:42
Right, so make sure when you set your id, it is a string.

Have you tried my suggestion 2?

**Comment by nam-co** [comment] 2017-03-04 14:44
Your suggestion No. 2 works, created_at what necessary to save, what do you think about the $message3 = Messages::find(1); is still showing the error

**Comment by baopham** [comment] 2017-03-04 14:45
Try `$message3 = Messages::find('1')`

You're passing in a number so it wouldn't parse correctly.

**Comment by nam-co** [comment] 2017-03-04 14:46
even with $message3 = Messages::find('1'); I get the same error

**Comment by baopham** [comment] 2017-03-04 14:51
do you have another record that you can test? Something that is not a number.

**Comment by nam-co** [comment] 2017-03-04 14:54
ok, I tried
1.  $message3 = Messages::where('order_id', '1')->first(); I got null (no error)
2.  $message3 = Messages::where('order_id', 1)->first(); I got error "MassAssignmentException in Model.php line 225: content" you can see it here https://rebilling.co/test2

**Comment by nam-co** [comment] 2017-03-04 14:56
let me try with created_at witch is a string

**Comment by baopham** [comment] 2017-03-04 14:58
No. I meant do you have another ID that is not exactly a number and use that to test `find`

**Comment by nam-co** [comment] 2017-03-04 15:00
but the id is a (String) and  sort: create_at (String)
I tried with content = "TAMBIEN claro que si\n\npero con return?" and got null

**Comment by baopham** [comment] 2017-03-04 15:02
Sorry but I don't understand what you meant. Can you be more clear in your response?

Find some *ID* that is more like a UUID and not a numeric.

**Comment by nam-co** [comment] 2017-03-04 15:04
ok , I saw a typo, I put in the table create_at missing the D, so I tried
$message3 = Messages::where('create_at', '2017-01-21 00:24:11')->first();
and got the same MassAssignmentException in Model.php line 225: content please see https://rebilling.co/test2

Im just trying to use where with multiple fields

**Comment by baopham** [comment] 2017-03-04 15:06
There are a few things and I have no idea what you are asking: 

1. `$message3 = Messages::find(1)` or `$message3 = Messages::find('1')` which I kept asking you to try a different ID.
2. `$message3 = Messages::where('create_at', '2017-01-21 00:24:11')->first();` which I think you already solved it by fixing the typo.

So I'm really confused about what you are asking.

**Comment by nam-co** [comment] 2017-03-04 15:08
is the same thing, I can query any results, they all show null or "MassAssignmentException in Model.php line 225: content" error
Im able to save, but not get any records

**Comment by baopham** [comment] 2017-03-04 15:11
Try to setup your fillable attributes in your model:   

```php
$fillable = ['create_at', 'order_id', ...]
```

**Comment by nam-co** [comment] 2017-03-04 15:25
I always thought fillable was just for saving, but it works :) , now this 2 work:
$message2 = Messages::where('create_at', '2017-01-21 00:24:11')->first();
$message3 = Messages::where('create_at', '567')->get();

but find by id still doesn't :
$message1 = Messages::find('58badb381838c5.44840949'); OR
$message1 = Messages::where('id', '1')->first();
they still produce the same error as my first message (DynamoDbException)

**Comment by baopham** [comment] 2017-03-04 15:27
> I always thought fillable was just for saving
Ah yeah, I'm using `Model::fill` to give you back the model object so that's why you're getting the mass assignment error. I should use a different method though.

Do you have a stack trace for me?

**Comment by nam-co** [comment] 2017-03-04 15:38
Sorry I don't understand what "stack trace" is, but the logs in laravel don't show any error, I tried with other fields and it works, maybe I shouldn't name the primary "id" but something like "my_id"

**Comment by nam-co** [comment] 2017-03-04 15:42
Next Aws\DynamoDb\Exception\DynamoDbException: Error executing "GetItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
 ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"} in /home/forge/rebilling.co/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:192
Stack trace:
#0 /home/forge/rebilling.co/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#3 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /home/forge/rebilling.co/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#6 /home/forge/rebilling.co/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /home/forge/rebilling.co/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /home/forge/rebilling.co/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait()
#15 /home/forge/rebilling.co/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command))
#16 /home/forge/rebilling.co/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(136): Aws\AwsClient->__call('getItem', Array)
#17 /home/forge/rebilling.co/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(211): BaoPham\DynamoDb\DynamoDbQueryBuilder->find(Array, Array)
#18 /home/forge/rebilling.co/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(157): BaoPham\DynamoDb\DynamoDbQueryBuilder->getAll(Array, 1)
#19 /home/forge/rebilling.co/app/Http/Controllers/FrontController.php(306): BaoPham\DynamoDb\DynamoDbQueryBuilder->first()

**Comment by baopham** [comment] 2017-03-04 15:44
You are not using composite key, are you?

**Comment by nam-co** [comment] 2017-03-04 15:46
All my model file is what I send you (+ the fillable), I don't think Im using a composite key

**Comment by nam-co** [comment] 2017-03-04 16:18
ok, I change the primary to primary_id and it work better, anyway found an error with this (“) “primary_id" in the json, so that might been the error?

Anyway $message1 = Messages::where('primary_id', '1')->first(); now works
but $message0 = Messages::find('1') still doesn't, but I can manage with the first one

**Comment by baopham** [comment] 2017-03-04 16:48
I have a feeling that your table doesn't have the correct primary key.

**Comment by nam-co** [comment] 2017-03-04 16:50
I get error: Illegal offset type in isset or empty

**Comment by baopham** [comment] 2017-03-04 16:50
Stack trace please?

**Comment by nam-co** [comment] 2017-03-04 16:52
[2017-03-04 11:50:07] local.ERROR: ErrorException: Illegal offset type in isset or empty in /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Support/Str.php:435
Stack trace:
#0 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Support/Str.php(435): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/home/forge/reb...', 435, Array)
#1 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(553): Illuminate\Support\Str::studly(Array)
#2 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(516): Illuminate\Database\Eloquent\Model->hasSetMutator(Array)
#3 /home/forge/rebilling.co/vendor/baopham/dynamodb/src/DynamoDbModel.php(181): Illuminate\Database\Eloquent\Model->setAttribute(Array, 1)
#4 /home/forge/rebilling.co/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(122): BaoPham\DynamoDb\DynamoDbModel->setId(1)
#5 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1316): BaoPham\DynamoDb\DynamoDbQueryBuilder->find(1)
#6 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1328): Illuminate\Database\Eloquent\Model->__call('find', Array)
#7 /home/forge/rebilling.co/app/Http/Controllers/FrontController.php(309): Illuminate\Database\Eloquent\Model::__callStatic('find', Array)
#8 [internal function]: App\Http\Controllers\FrontController->test2()
#9 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#10 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('test2', Array)
#11 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\FrontController), 'test2')
#12 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#13 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#14 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /home/forge/rebilling.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /home/forge/rebilling.co/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}

**Comment by baopham** [comment] 2017-03-04 16:56
`DynamoDbQueryBuilder->find(1)` <--- this is why I would like you to try a different ID value that is not a numeric. E.g. `Message::find('abcdefg')`. Additionally, can you give me your updated model class and confirm what is your primary key now? is it `id` or `primary_id`?

**Comment by nam-co** [comment] 2017-03-04 16:57
class Messages extends \BaoPham\DynamoDb\DynamoDbModel
{
	protected $table = 'Rebilling_messages';
	protected $fillable = ['create_at', 'order_id', 'content', 'files', 'primary_id', 'from'];
	protected $primaryKey = ['primary_id'];

**Comment by nam-co** [comment] 2017-03-04 16:57
in controller 
$message = Messages::find('1');

**Comment by baopham** [comment] 2017-03-04 16:58
Thanks. Now can you try a different ID value please? Nothing numeric.

**Comment by nam-co** [comment] 2017-03-04 17:00
I tried $message = Messages::find('hello'); same error

baopham with the DB in digital ocean Im getting an execution time of 0.025 and with Dynamo on AWS Im getting a 0.19 is this normal? I thought Dynamo was faster or is just local vs aws servers

**Comment by baopham** [comment] 2017-03-04 17:03
> $message = Messages::find('hello'); same error
Ok, I will have to find sometime and reproduce this.

> with the DB in digital ocean Im getting an execution time of 0.025 and with Dynamo on AWS Im getting a 0.19 is this normal?

Umm, I don't understand. Are you testing all locally?

>  I thought Dynamo was faster
Depends, really on how you design your tables.

> is just local vs aws servers
Requests made from local environment tend to be slower.

**Comment by nam-co** [comment] 2017-03-04 17:09
When I mean local I mean the same DB in the digital ocean server where the app is running

Im getting the execution time with 
$message = Messages::where('primary_id', '1')->first();
$time = microtime(true) - $_SERVER["REQUEST_TIME_FLOAT"];
echo "Process Time sql: {$time}";

and then in another link Im using the Digital Ocean db

**Comment by baopham** [comment] 2017-03-04 17:10
I'm afraid that this question is out of scope of this library. There are a lot of factors to take into account and I don't know how your DB, server, etc. are setup.

**Comment by nam-co** [comment] 2017-03-04 17:11
true, well I would like to thanks you for your help B, appreciate it a lot

**Comment by baopham** [comment] 2017-03-04 17:12
No problem. As for the `Message::find(...)` error, I will try to reproduce it on my end but probably won't be able to until next weekend.

**Comment by baopham** [comment] 2017-04-25 12:23
Sorry, couldn't find the time to work on this... I'll leave this open for now

**Comment by nam-co** [comment] 2017-08-02 21:05
Hi baopham, hope your ok, I was wondering, did you ever find a fix for the error? 

Error executing "GetItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}
fit happens with both
$message = Messages::find('59822b2cda8650.74115649');
and
$message = Messages::where('id', $id);

Appreciate the help

**Comment by nam-co** [comment] 2017-08-02 21:37
Hi baopham, I found a way :), once a gain thanks for the great package

**Comment by baopham** [comment] 2017-08-03 00:56
Great! Congrats! Closing issue.

**Closed by baopham** 2017-08-03 00:56 UTC

**Comment by KriiV** [comment] 2018-06-25 02:27
@nam-co Would you be able to share your solution? having the same issue

**Comment by nam-co** [comment] 2018-06-25 16:16
Hi @KriiV tone honest I don't remember, it was like a year a go, but to be honest at the end I choose to use a regular mysql instead of AWS

**Comment by baopham** [comment] 2018-06-25 16:20
@KriiV feel free to create a new issue.

**Comment by krupali-mbarc** [comment] 2021-06-15 13:19
hi @nam-co i'm facing this same issue.Can you please suggest the solution for find and where fucniton error.

**Comment by krupali-mbarc** [comment] 2021-06-15 13:20
> Hi baopham, hope your ok, I was wondering, did you ever find a fix for the error?
> 
> Error executing "GetItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
> ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}
> fit happens with both
> $message = Messages::find('59822b2cda8650.74115649');
> and
> $message = Messages::where('id', $id);
> 
> Appreciate the help

fsdfdsf

**Comment by krupali-mbarc** [comment] 2021-06-15 13:22
> Hi baopham, hope your ok, I was wondering, did you ever find a fix for the error?
> 
> Error executing "GetItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
> ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}
> fit happens with both
> $message = Messages::find('59822b2cda8650.74115649');
> and
> $message = Messages::where('id', $id);
> 
> Appreciate the help

Hi @nam-co i'm stiil facing this above error issue for find and where query. Can you please help me out to resolve issue or error?

**Comment by thomasedwards** [comment] 2021-06-15 14:23
Can you post your code where you call the query?

**Comment by nam-co** [comment] 2021-06-15 15:19
Hi I choose to use a regular mysql instead of AWS because all this problems, this is an old issue, But I see people are still having the same issues

**Comment by thomasedwards** [comment] 2021-06-17 13:57
Sorry I meant to tag @krupali-mbarc as they asked the question two days ago on a four year old thread, not the author of the original thread. Hundreds of thousands of queries are made using this framework so I’m not convinced that there is an issue here, other than not understanding how it works. Sorry it didn’t work out for you.
